name: pro_counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_flip_counter: ^0.2.5
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  hydrated_bloc: ^8.0.0
  intl: ^0.17.0
  path_provider: ^2.0.11
  replay_bloc: ^0.2.2

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  mocktail: ^0.2.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
